name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  lint:
    name: Lint Workflows & Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          fail_level: error
          filter_mode: nofilter
